predict:
  name: "Predict spaghetti"
  description: "Runs the Obico ML model whether the given image has spaghetti"
  fields:
    obico_host:
      description: "Obico ML Server URL."
      example: "http://192.168.1.123:3333"
      required: true
      selector:
        text:
    obico_auth_token:
      description: "Obico ML Server authentication token."
      example: "obico_api_secret"
      required: true
      selector:
        text:
    image_url:
      description: "URL of the image for spaghetti detection."
      example: "https://your-image-url.jpg"
      required: true
      selector:
        text: