blueprint:
  name: Klipper Printer - Spaghetti Detection
  description: Spaghetti Detection for any Klipper Printer
  domain: automation
  input:
    home_assistant_host:
      name: Home Assistant Host
      description: Home Assistant host
      default: "http://127.0.0.1:8123"
    obico_host:
      name: Obico ML API Host
      description: Obico ML API host
      default: "http://127.0.0.1:3333"
    obico_auth_token:
      name: Obico ML API Auth Token
      description: Obico ML API authentication token
      default: "obico_api_secret"
    detection_frequency:
      name: Detection Frequency
      description: The detection algorithm will run in every defined seconds
      default: "/5"
      selector:
        select:
          options:
            - label: Every second
              value: "/1"
            - label: Every 5 seconds
              value: "/5"
            - label: Every 10 seconds
              value: "/10"
            - label: Every 30 seconds
              value: "/30"
            - label: Every 60 seconds
              value: "/59"
          multiple: false
          mode: dropdown
    auto_turn_on_light:
      name: Automatically Turn On Printer Lights
      description: Turns on printer lights before spaghetti detection operation
      default: true
      selector:
        boolean:
    notification_settings:
      name: Notification Settings
      description: Type of notification to send after detecting a failure
      default: standard
      selector:
        select:
          mode: dropdown
          options:
            - label: Critical Notification
              value: critical
            - label: Standard Notification
              value: standard
            - label: None
              value: none
    failure_action:
      name: On Failure Action
      description: What to do after detecting a failure
      default: pause
      selector:
        select:
          mode: dropdown
          options:
            - label: Pause
              value: pause
            - label: Stop
              value: stop
            - label: Warn
              value: warn
    notification_service:
      name: Mobile devices notification service
      description: >-
        The notification service for mobile devices (eg. notify.mobile_app_<your_device_id_here>).
        You can provide both a notify group or a single notify device here.
      default: notify.notify
      selector:
        text:
    printer_print_status_sensor:
      name: Print Status Sensor
      description: Select the printer's Print Status Sensor (Bambu Printers) or Current Print State Sensor (Klipper Printers)
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: enum
    printer_current_stage_sensor:
      name: Current Stage Sensor
      description: Select the printer's Current Stage Sensor (Bambu Printers) or Current Print State Sensor (Klipper Printers - same as above)
      selector:
        entity:
          filter:
            - domain: sensor
              device_class: enum
    printer_camera:
      name: Camera Entity
      description: Select the camera entity which will be used for spaghetti detection
      selector:
        entity:
          filter:
            - domain: camera
    printer_pause_button:
      name: Pause Button Entity
      description: Select the printer's pause button entity
      selector:
        entity:
          filter:
            - domain: button
    printer_resume_button:
      name: Resume Button Entity
      description: Select the printer's resume button entity
      selector:
        entity:
          filter:
            - domain: button
    printer_stop_button:
      name: Stop Button Entity
      description: Select the printer's stop (or cancel print) button entity
      selector:
        entity:
          filter:
            - domain: button
    printer_chamber_light:
      name: Light
      description: Select the light entity which will optionally be turned on at print start
      selector:
        entity:
          filter:
            - domain: light
    printer_chamber_light:
      name: Light
      description: Select the light entity which will optionally be turned on at print start
      selector:
        entity:
          filter:
            - domain: light

    ### TO DO: Add options to change Automoation calculation thresholds - see https://github.com/nberktumer/ha-bambu-lab-p1-spaghetti-detection/issues/2#issuecomment-1937766963

variables:
  HOME_ASSISTANT_HOST_VAR: !input home_assistant_host
  PRINTER_CAMERA_VAR: !input printer_camera
  FAILURE_ACTION_VAR: !input failure_action
  NOTIFICATION_SETTINGS_VAR: !input notification_settings
  DETECTION_FREQUENCY_VAR: !input detection_frequency
mode: single
max_exceeded: silent
trigger:
  - platform: state
    entity_id:
      - !input printer_current_stage_sensor
    to: printing
    id: PRINTER_STATE_CHANGE
  - platform: event
    event_type: mobile_app_notification_action
    id: PAUSE_PRINTING
    event_data:
      action: PAUSE_PRINTING
  - platform: event
    event_type: mobile_app_notification_action
    id: RESUME_PRINTING
    event_data:
      action: RESUME_PRINTING
  - platform: event
    event_type: mobile_app_notification_action
    id: STOP_PRINTING
    event_data:
      action: STOP_PRINTING
  # Detection trigger
  - trigger: time_pattern
    id: DETECTION_TRIGGER
    seconds: !input detection_frequency
condition: [ ]
action:
  - choose:
      # Print start actions
      - conditions:
          - condition: trigger
            id: PRINTER_STATE_CHANGE
        sequence:
          - service: number.set_value
            data:
              value: 0
            target:
              entity_id:
                - number.spaghetti_detection_current_frame_number
                - number.spaghetti_detection_ewm_mean
                - number.spaghetti_detection_rolling_mean_short
                - number.spaghetti_detection_rolling_mean_long
                - number.spaghetti_detection_normalized_p
                - number.spaghetti_detection_adjusted_ewm_mean
                - number.spaghetti_detection_p_sum
          - if:
            - condition: and
              conditions:
              - condition: state
                entity_id: !input printer_chamber_light
                state: 'off'
              - condition: template
                value_template: !input auto_turn_on_light
            then:
              - service: light.turn_on
                target:
                  entity_id:
                    - !input printer_chamber_light

      # Notification actions
      - conditions:
          - condition: trigger
            id:
              - PAUSE_PRINTING
              - RESUME_PRINTING
              - STOP_PRINTING
        sequence:
          - choose:
              - conditions:
                  - condition: trigger
                    id:
                      - PAUSE_PRINTING
                sequence:
                  - service: button.press
                    data: { }
                    target:
                      entity_id: !input printer_pause_button
              - conditions:
                  - condition: trigger
                    id: RESUME_PRINTING
                sequence:
                  - service: button.press
                    data: { }
                    target:
                      entity_id: !input printer_resume_button
              - conditions:
                  - condition: trigger
                    id: STOP_PRINTING
                sequence:
                  - service: button.press
                    data: { }
                    target:
                      entity_id: !input printer_stop_button

      # Notification actions
      - conditions:
          - condition: trigger
            id: DETECTION_TRIGGER
        sequence:
          - if:
              - condition: not
                conditions:
                  - condition: state
                    entity_id: !input printer_print_status_sensor
                    # state: running
                    state: printing
            then:
              - stop: ""
          - if:
              - condition: template
                value_template: "{{ now().second % DETECTION_FREQUENCY_VAR > 0 }}"
            then:
              - stop: ""
          - if:
            - condition: and
              conditions:
              - condition: state
                entity_id: !input printer_chamber_light
                state: 'off'
              - condition: template
                value_template: !input auto_turn_on_light
            then:
              - service: light.turn_on
                target:
                  entity_id:
                    - !input printer_chamber_light
          - service: spaghetti_detection.predict
            data:
              obico_host: !input obico_host
              obico_auth_token: !input obico_auth_token
              image_url: "{{ HOME_ASSISTANT_HOST_VAR }}{{ state_attr(PRINTER_CAMERA_VAR, 'entity_picture') }}"
            response_variable: result

          - service: number.set_value
            data:
              value: "{{ result.result.detections | map(attribute=1) | sum | float }}"
            target:
              entity_id: number.spaghetti_detection_p_sum

          - service: number.set_value
            data:
              value: "{{ states('number.spaghetti_detection_current_frame_number') | float + 1 }}"
            target:
              entity_id: number.spaghetti_detection_current_frame_number

          - service: number.set_value
            data:
              value: "{{ states('number.spaghetti_detection_lifetime_frame_number') | float + 1 }}"
            target:
              entity_id: number.spaghetti_detection_lifetime_frame_number

          - service: number.set_value
            data:
              value: "{{ (states('number.spaghetti_detection_p_sum') | float) * (2 / (12 + 1)) + (states('number.spaghetti_detection_ewm_mean') | float) * (1 - (2 / (12 + 1))) }}"
            target:
              entity_id: number.spaghetti_detection_ewm_mean

          - service: number.set_value
            data:
              value: "{{ (states('number.spaghetti_detection_rolling_mean_short') | float) + ((states('number.spaghetti_detection_p_sum') | float) - (states('number.spaghetti_detection_rolling_mean_short') | float)) / (310 if 310 <= (states('number.spaghetti_detection_current_frame_number') | float) else (states('number.spaghetti_detection_current_frame_number') | float) + 1) }}"
            target:
              entity_id: number.spaghetti_detection_rolling_mean_short

          - service: number.set_value
            data:
              value: "{{ (states('number.spaghetti_detection_rolling_mean_long') | float) + ((states('number.spaghetti_detection_p_sum') | float) - (states('number.spaghetti_detection_rolling_mean_long') | float)) / (7200 if 7200 <= (states('number.spaghetti_detection_lifetime_frame_number') | float) else (states('number.spaghetti_detection_lifetime_frame_number') | float) + 1) }}"
              entity_id: number.spaghetti_detection_rolling_mean_long

          - if:
              - condition: numeric_state
                entity_id: number.spaghetti_detection_current_frame_number
                below: 30
            then:
              - stop: ""
            alias: if current_frame_num < 30

          - service: number.set_value
            data:
              value: >-
                {{ (states('number.spaghetti_detection_ewm_mean') | float) - (states('number.spaghetti_detection_rolling_mean_long') | float) }}
            target:
              entity_id: number.spaghetti_detection_adjusted_ewm_mean

          - service: number.set_value
            data:
              value: >-
                {{ ((states('number.spaghetti_detection_rolling_mean_short') | float) - (states('number.spaghetti_detection_rolling_mean_long') | float)) * 3.8 }}
            target:
              entity_id: number.spaghetti_detection_rolling_mean_diff

          - service: number.set_value
            data:
              value: >-
                {{ min(0.78, max(0.33, (states('number.spaghetti_detection_rolling_mean_diff') | float))) }}
            target:
              entity_id: number.spaghetti_detection_thresh_warning

          - service: number.set_value
            data:
              value: >-
                {{ (states('number.spaghetti_detection_thresh_warning') | float) * 1.75 }}
            target:
              entity_id: number.spaghetti_detection_thresh_failure

          - service: number.set_value
            data:
              value: >-
                {{ (states('number.spaghetti_detection_ewm_mean') | float) - (states('number.spaghetti_detection_rolling_mean_long') | float) }}
            target:
              entity_id: number.spaghetti_detection_p

          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: number.spaghetti_detection_p
                    above: number.spaghetti_detection_thresh_failure
                sequence:
                  - service: number.set_value
                    data:
                      value: >-
                        {{ min(1.0, max(2.0 / 3.0, ((((states('number.spaghetti_detection_p') | float) - (states('number.spaghetti_detection_thresh_failure') | float)) * (1.0 - 2.0 / 3.0)) / ((states('number.spaghetti_detection_thresh_failure') | float) * 1.5 - (states('number.spaghetti_detection_thresh_failure') | float))) + 2.0 / 3.0)) }}
                    target:
                      entity_id: number.spaghetti_detection_normalized_p
              - conditions:
                  - condition: numeric_state
                    entity_id: number.spaghetti_detection_p
                    above: number.spaghetti_detection_thresh_warning
                sequence:
                  - service: number.set_value
                    data:
                      value: >-
                        {{ min(2.0 / 3.0, max(1.0 / 3.0, ((((states('number.spaghetti_detection_p') | float) - (states('number.spaghetti_detection_thresh_warning') | float)) * (2.0 / 3.0 - 1.0 / 3.0)) / ((states('number.spaghetti_detection_thresh_failure') | float) - (states('number.spaghetti_detection_thresh_warning') | float))) + 1.0 / 3.0)) }}
                    target:
                      entity_id: number.spaghetti_detection_normalized_p
            default:
              - service: number.set_value
                data:
                  value: >-
                    {{ min(1.0 / 3.0, max(0, ((states('number.spaghetti_detection_p') | float) * 1.0 / 3.0) / (states('number.spaghetti_detection_thresh_warning') | float))) }}
                target:
                  entity_id: number.spaghetti_detection_normalized_p

          # if adjusted_ewm_mean < THRESHOLD_LOW
          - if:
              - condition: numeric_state
                entity_id: number.spaghetti_detection_adjusted_ewm_mean
                below: 0.38
            then:
              - stop: ""

          #  if adjusted_ewm_mean <= THRESHOLD_HIGH and adjusted_ewm_mean <= rolling_mean_diff
          - if:
              - condition: and
                conditions:
                  - condition: numeric_state
                    entity_id: number.spaghetti_detection_adjusted_ewm_mean
                    below: 0.78
                  - condition: numeric_state
                    entity_id: number.spaghetti_detection_adjusted_ewm_mean
                    below: number.spaghetti_detection_rolling_mean_diff
            then:
              - stop: ""

          # if now() - last_notify_time < 1min
          - if:
              - condition: template
                value_template: >-
                  {{ now() - states('datetime.spaghetti_detection_last_notify_time') | as_datetime | as_local < timedelta(minutes=1) }}
            then:
              - stop: ""
            alias: >-
              if now() - last_notify_time < 1min

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ FAILURE_ACTION_VAR == 'pause' }}"
                sequence:
                  - service: button.press
                    data: { }
                    target:
                      entity_id: !input printer_pause_button
              - conditions:
                  - condition: template
                    value_template: "{{ FAILURE_ACTION_VAR == 'stop' }}"
                sequence:
                  - service: button.press
                    data: { }
                    target:
                      entity_id: !input printer_stop_button

          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ NOTIFICATION_SETTINGS_VAR == 'critical' }}"
                sequence:
                  - service: !input notification_service
                    data:
                      title: "Spaghetti Detected"
                      message: "Confidence: {{ (states('number.spaghetti_detection_normalized_p') | float * 100) | int }}%"
                      data:
                        image: "{{ HOME_ASSISTANT_HOST_VAR }}{{ state_attr(PRINTER_CAMERA_VAR, 'entity_picture') }}"
                        ttl: 0
                        priority: high
                        channel: alarm_stream
                        push:
                          sound:
                            name: default
                            critical: 1
                            volume: 0.75
                        actions:
                          - action: RESUME_PRINTING
                            title: Resume Printing
                          - action: STOP_PRINTING
                            title: Stop Printing
              - conditions:
                  - condition: template
                    value_template: "{{ NOTIFICATION_SETTINGS_VAR == 'standard' }}"
                sequence:
                  - service: !input notification_service
                    data:
                      title: "Spaghetti Detected"
                      message: "Confidence: {{ (states('number.spaghetti_detection_normalized_p') | float * 100) | int }}%"
                      data:
                        image: "{{ HOME_ASSISTANT_HOST_VAR }}{{ state_attr(PRINTER_CAMERA_VAR, 'entity_picture') }}"
                        actions:
                          - action: RESUME_PRINTING
                            title: Resume Printing
                          - action: STOP_PRINTING
                            title: Stop Printing
          - service: number.set_value
            data:
              value: 0
            target:
              entity_id:
                - number.spaghetti_detection_current_frame_number
                - number.spaghetti_detection_ewm_mean
                - number.spaghetti_detection_rolling_mean_short
                - number.spaghetti_detection_rolling_mean_long
                - number.spaghetti_detection_normalized_p
                - number.spaghetti_detection_adjusted_ewm_mean
                - number.spaghetti_detection_p_sum
          - service: datetime.set_value
            data:
              datetime: >-
                {{ now() }}
            target:
              entity_id: datetime.spaghetti_detection_last_notify_time
